/*************************************************************************//**
 *****************************************************************************
 * @file   anim.h
 * @brief  
 * @author Kerr
 * @date   Aug 22 2020
 *****************************************************************************
 *****************************************************************************/

#include "console.h"
#include "stdio.h"

void anim() 
{
	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #          #   #                                                   #\n");
	printf("      #           # #                                                    #\n");
	printf("      #            #                                                     #\n");
	printf("      #            #                                                     #\n");
	printf("      #            #                                                     #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #          #   # ######                                            #\n");
	printf("      #           # #  #                                                 #\n");
	printf("      #            #   #####                                             #\n");
	printf("      #            #   #                                                 #\n");
	printf("      #            #   ######                                            #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #          #   # ###### ######                                     #\n");
	printf("      #           # #  #      #                                          #\n");
	printf("      #            #   #####  #####                                      #\n");
	printf("      #            #   #      #                                          #\n");
	printf("      #            #   ###### ######                                     #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #          #   # ###### ###### ######                              #\n");
	printf("      #           # #  #      #          #                               #\n");
	printf("      #            #   #####  #####     #                                #\n");
	printf("      #            #   #      #        #                                 #\n");
	printf("      #            #   ###### ###### ######                              #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #          #   # ###### ###### ###### #   #                        #\n");
	printf("      #           # #  #      #          #   # #                         #\n");
	printf("      #            #   #####  #####     #     #                          #\n");
	printf("      #            #   #      #        #      #                          #\n");
	printf("      #            #   ###### ###### ######   #                          #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #                      #\n");
	printf("      #          #   # ###### ###### ###### #   # #                      #\n");
	printf("      #           # #  #      #          #   # #  #                      #\n");
	printf("      #            #   #####  #####     #     #                          #\n");
	printf("      #            #   #      #        #      #                          #\n");
	printf("      #            #   ###### ###### ######   #                          #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #                      #\n");
	printf("      #          #   # ###### ###### ###### #   # #                      #\n");
	printf("      #           # #  #      #          #   # #  #                      #\n");
	printf("      #            #   #####  #####     #     #   #                      #\n");
	printf("      #            #   #      #        #      #   #                      #\n");
	printf("      #            #   ###### ###### ######   #   #                      #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #                      #\n");
	printf("      #          #   # ###### ###### ###### #   # #                      #\n");
	printf("      #           # #  #      #          #   # #  #                      #\n");
	printf("      #            #   #####  #####     #     #   #                      #\n");
	printf("      #            #   #      #        #      #   #                      #\n");
	printf("      #            #   ###### ###### ######   #   ####                   #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #                      #\n");
	printf("      #          #   # ###### ###### ###### #   # #                      #\n");
	printf("      #           # #  #      #          #   # #  #                      #\n");
	printf("      #            #   #####  #####     #     #   #                      #\n");
	printf("      #            #   #      #        #      #   #                      #\n");
	printf("      #            #   ###### ###### ######   #   #######                #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #                      #\n");
	printf("      #          #   # ###### ###### ###### #   # #                      #\n");
	printf("      #           # #  #      #          #   # #  #     #                #\n");
	printf("      #            #   #####  #####     #     #   #     #                #\n");
	printf("      #            #   #      #        #      #   #     #                #\n");
	printf("      #            #   ###### ###### ######   #   #######                #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #    ##                #\n");
	printf("      #          #   # ###### ###### ###### #   # #     #                #\n");
	printf("      #           # #  #      #          #   # #  #     #                #\n");
	printf("      #            #   #####  #####     #     #   #     #                #\n");
	printf("      #            #   #      #        #      #   #     #                #\n");
	printf("      #            #   ###### ###### ######   #   #######                #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #######                #\n");
	printf("      #          #   # ###### ###### ###### #   # #     #                #\n");
	printf("      #           # #  #      #          #   # #  #     #                #\n");
	printf("      #            #   #####  #####     #     #   #     #                #\n");
	printf("      #            #   #      #        #      #   #     #                #\n");
	printf("      #            #   ###### ###### ######   #   #######                #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #######                #\n");
	printf("      #          #   # ###### ###### ###### #   # #     #  ####          #\n");
	printf("      #           # #  #      #          #   # #  #     # #              #\n");
	printf("      #            #   #####  #####     #     #   #     #  ####          #\n");
	printf("      #            #   #      #        #      #   #     #      #         #\n");
	printf("      #            #   ###### ###### ######   #   #######  ####          #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #            Designed by YoungYoung Kerr Brain TT LeiHong            #\n");
	printf("      #                                                                  #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf("      ====================================================================\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                           #######                #\n");
	printf("      #          #   # ###### ###### ###### #   # #     #  ####          #\n");
	printf("      #           # #  #      #          #   # #  #     # #              #\n");
	printf("      #            #   #####  #####     #     #   #     #  ####          #\n");
	printf("      #            #   #      #        #      #   #     #      #         #\n");
	printf("      #            #   ###### ###### ######   #   #######  ####          #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #                                                                  #\n");
	printf("      #            Designed by YoungYoung Kerr Brain TT LeiHong            #\n");
	printf("      #                         TONGJI UNIVERSITY                        #\n");
	printf("      ====================================================================\n");
	milli_delay(DELAY_TIME);


}